### PR TITLE
Reduced the number of locals on stconrol and ftrace

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by thegrb93** [comment]
Try https://github.com/wiremod/wire/pull/2026 first and see if that works

**Comment by thegrb93** [comment]
Did you try it?

**Comment by dvdvideo1234** [comment]
I am working on reduce locals copy of my addon ;)

**Comment by dvdvideo1234** [comment]
I did try it... And it was working after I added the one local function. Tomorrow I tested it again and gave me the error. Let me fix that.

**Comment by dvdvideo1234** [comment]
@thegrb93 I will revert my addon to the point where I localized the overhead and apply the change proposed by @bigdogmat and report it here. In the meantime, you can use https://github.com/wiremod/wire-extras/pull/86/commits/e5e9e5f9d5b65f51f7e6feebe46537bc21f1d8f8 to overcome this error.

**Comment by dvdvideo1234** [comment]
Link to the testing methodology:

https://github.com/wiremod/wire/issues/2025#issuecomment-587875767

**Comment by thegrb93** [comment]
This change isn't needed anymore, right?

**Comment by dvdvideo1234** [comment]
@thegrb93

No. It is still needed because I've removed the reference to the E2 chip that was passed as an argument to many of the functions. It is passed only on instance creation.
I've added zero-crossing detection, adjusted the dumping, fixed other things like the tracer ignoring its length when sampled in world-base rays, updated the description, added second description string when registering the addon ;)

**Comment by dvdvideo1234** [comment]
@thegrb93 

If you mean only https://github.com/wiremod/wire-extras/pull/86/commits/e5e9e5f9d5b65f51f7e6feebe46537bc21f1d8f8 it can pas without this commit, but I still prefer better codebase as good is it with wire, the better.

**Comment by thegrb93** [comment]
Oh I didn't notice you added a lot more changes. Will look at them soon.

**Comment by dvdvideo1234** [comment]
I added (TL) and updated (ZN2) tuning methods

**Comment by thegrb93** [comment]
Sorry for the long wait. This PR is just too big to review. I just glanced over the code and didn't see anything malicious and I ran it in my game to make sure no lua errors. I'm assuming you use this library and its working fine so I think we can merge.

**Comment by dvdvideo1234** [comment]
@thegrb93 Yes, I am using it in day to day basis.

**Comment by TomyLobo** [comment]
Neither of you said anything about why we need to reduce the number of locals at all

**Comment by thegrb93** [comment]
It doesn't anymore since the preprocessor was updated, but there's other improvements added as well.

**Pull request merged**
