### PR TITLE
Synchronize ftrace with the origin repository

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by TomyLobo** [comment]
I know it has already been added a while ago, but what does this extension even do?
I see a lot of buzzwords flying around but no substance...

**Comment by dvdvideo1234** [comment]
@TomyLobo

Adds: Dedicated ( initialized only once and used multiple times along the code ) tracer
and controller OOP classes ( objects manipulated via class methods ) with coding effective API

1. Tracers with hit and ray configuration. The difference with wire rangers is that this is a dedicated class being initialized once and used as many times as it is needed, not creating an instance on every E2 tick and later wipe that instance out. It can extract every aspect of [the trace result structure](https://wiki.garrysmod.com/page/Structures/TraceResult) returned and it can me samples locally ( origin and direction relative to `entity` or `pos`/`dir`/`ang` ) or globally ( entity is not available and `pos`/`dir`/`ang` are treated world-space data ). Also, it has better performance than the regular wire rangers.

2. State controller class that creates LQ-PID controllers with static or dynamic sampling time. They are used generally for every king of automatic control that is needed in Wiremod. Supports a bunch of general tuning methods, I studied at [the university](https://tu-sofia.bg/) and can be initialized as a relay, linear or power controller. The error `E` with power `P` can be zero, positive or negative number. When zero, the output is calculated as [relay](https://en.wikipedia.org/wiki/Relay), when equal to 1, we have the [classic PID controller](https://en.wikipedia.org/wiki/PID_controller) when the power is 2 the error has quadratic relation `E^2`, 3, for cubic and so on needed for aero-propeller systems. Negative powers will be treated as error square root `1/E^P`. The user can put even fractional powers `P` to each term. It has a lot of possibilities. The only limis is your imagination.

**Comment by dvdvideo1234** [comment]
Currently, the trace skips the entity hist list as there is no data type for it. This PR fixes that and fixes some description typos

**Comment by dvdvideo1234** [comment]
@TomyLobo If you need additional information on this you can check the [wiki page](https://github.com/dvdvideo1234/ControlSystemsE2/wiki).

**Pull request merged**
