### PR TITLE
fix gui wiring

### PR DESCRIPTION
**Pull request by mms92**
the tool was not working , probably due to some scope problem with the variable , i changed the library used to trigger the var initialisation , draw of the gui and wirelink reception , from usermessage to net

### CODE REVIEW

**Comment by mms92** [comment]
fixed wirelink creation

**Comment by mms92** [comment]
up ?

**Comment by thegrb93** [comment]
Hey, I'm getting lua error because von is missing. Any chance this can have von dependence removed as well?

**Comment by mms92** [comment]
von is part of the wire library , found here https://github.com/wiremod/wire/blob/master/lua/wire/von.lua , so no need to switch to json , but instead maybe just add some include i think

**Comment by thegrb93** [comment]
That's weird. Wonder why I got attempt to index global 'von' (a nil value). Anyway, I tested it and it works

**Comment by bigdogmat** [comment]
It's part of `WireLib` now, https://github.com/wiremod/wire/blob/master/lua/wire/von.lua#L608-L609

**Comment by mms92** [comment]
bigdogmat , do i need to index it localy to be sure that problem will not happen again ?

**Comment by bigdogmat** [comment]
Index it from `WireLib`

**Comment by mms92** [comment]
like von = Wirelib.von ?

**Comment by thegrb93** [comment]
Yeah WireLib.von

**Comment by mms92** [comment]
ok , apparently , i need to create a new branch , and so a new pull request because the i maybe deleted the branch where i modified that file , so , do you merge this one and i create a pull for the wirelib.von 
 problem or i create a brand new pull request for all that story ?

**Comment by thegrb93** [comment]
I'd just make a new pr

**Comment by mms92** [comment]
ok so , i close this one and create a new

**Comment by mms92** [comment]
here it is https://github.com/wiremod/wire-extras/pull/61

**Pull request closed without merging**
