### PR TITLE
Added: Sensors and controllers OOP standart GMOD interfaces

### PR DESCRIPTION
**Pull request by dvdvideo1234**
Added: Sensor and controller OOP for the standard E2 interface in Garry's mod

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Example E2 script for a hover entity at a distance to the ground will be coded as follows:
```
@name Test Control
@inputs But RF
@outputs PV CN TT EE RR
@persist T:fsensor E:entity C:stcontroller
@trigger 
@model models/props_phx/construct/metal_wire1x1x1.mdl

runOnTick(1)

if(first() || dupefinished())
{
    E = entity()
    T = E:setFSensor(E:massCenterL(),vec(0,0,1), -225):addClassHit("prop_physics")
    C = newStController():setGains(1700, 6800, 7800):setWindup(-9000,9000):dumpConsole("TEST")
    E:setMass(250)
}

PV = T:smpLocal():getFractionLength()
CN = C:setState(RF, PV):setToggle(But):getControl()

TT = C:getTimeDelta()

E:applyForce(CN * vec(0,0,1))

EE = C:getError()
RR = C:getTimeRatio()
BB = C:getTimeBench()
```

**Comment by dvdvideo1234** [comment]
Controller dump:
```
[TEST][X][(GpFpNr)-PID][2056.212621572] Data:
 Human: [false] {V=0, B=0}
 Gains: {P=1700, I=3400, D=7800}
 Power: {P=1.1, I=0.5, D=1}
 Limit: {D=-9000, U=9000}
 Error: {O=0, N=0}
 Value: [0] {P=0, I=0, D=0}
 Flags: [false] {C=false, R=false, I=true}
```

**Comment by dvdvideo1234** [comment]
Hello, is it ready to be merged @AbigailBuccaneer @TomyLobo @Divran

**Comment by TomyLobo** [comment]
wat is this?

**Comment by TomyLobo** [comment]
I was being a bit facetious, because you highlighted me as if i should know what this is.
But there actually is no description of what this does or why.
So I stand by my original question.

**Comment by dvdvideo1234** [comment]
@TomyLobo 
These two types are OOP PID-controller and tracer for E2

**Comment by dvdvideo1234** [comment]
@TomyLobo

Sorry, I meant @thegrb93... Anyway, to put it in short why this PR gives additional degree of freedom for E2..
It contains object oriented fast preforming traces and PID-controllers, which with the right kind of tuning
can do very neat things. Both types are supposed to be `@persist` and they are created only once and used all the
time trough the `E2`'s routine. The `FSensor` type can create two kinds of objects, which preform the trace differently.
For the `local` `FSensor`, you need to provide `local` parameters as position and direction and for the `world` one,
as the name suggests it is created using `world` space parameters. The current `ranger` type needs only world-space
parameters and it also must be created in every iteration rendering the target `E2` much slower and thus, lagging the
server. This also becomes quite leggy, when you try to `localize` the `ranger` to an entity. To do that you currently
have to recalculate the starting position with six vector multiplications and additions. Now imagine having ten `rangers`..
The same idea is applied over the `state controller` object, because it has high performance rate ( controller calculation
time over gmod tick is about 0.001% ). It is also initialized inside `if(first() || dupefinished()){}` so is again created
once and used multiple times in every iteration. It is also quite packed, because one PID controller done in E2 requites
20-30 lines of code and about 8-10 persist variables to support the most used cases in the real world. We do not have to
forget all the internal variables one controller has and also the past values of the error and time to calculate the
derivative and integral. Now imagine you are making a hovercraft with four controllers...

With this controlling a trace distance becomes a breeze and one line of code.

**Comment by thegrb93** [comment]
I'm not very active in e2 development so i'm not the best to ask, but it looks fine and wire-extras is all about feature bloat so seems fine to me.

**Comment by thegrb93** [comment]
The only weirdness I see is that you're using SysTime and I'm not sure why.

**Comment by dvdvideo1234** [comment]
@thegrb93 

That's because I need to calculate the time between two E2 ticks helping me to calculate the derivative and the integral very precisely.

**Comment by thegrb93** [comment]
I think you need to use CurTime because SysTime doesn't have as good accuracy and in-game simulation is ran with CurTime

**Comment by dvdvideo1234** [comment]
Hello, 

Regarding [SysTime](http://wiki.garrysmod.com/page/Global/SysTime), [CurTime](http://wiki.garrysmod.com/page/Global/CurTime) and [RealTime](http://wiki.garrysmod.com/page/Global/RealTime), I noticed that my integral was a bit off when I paused the game, the PID controller stopped calculating the output control signal in a brief moment. If I hit `ESC` and stay in the menu for some time the process I was controlling was left without control signal..


NOTE | this is a synchronised value and affected by various factors such as host_timescale (or game.GetTimeScale) and the server being paused - either by sv_pausable or all players disconnecting.
-- | --

**Comment by dvdvideo1234** [comment]
@thegrb93 
So far I am pleased how it works. Gives a less more OPS and execution time is cut in half:

image

**Comment by dvdvideo1234** [comment]
@Divran  @AbigailBuccaneer  Is it good. Merge pls

**Comment by AbigailBuccaneer** [comment]
I don't have time to review `wire-extras` contributions, I'm not going to approve or deny this.

**Comment by thegrb93** [comment]
It's working fine. Just merge it.

**Comment by dvdvideo1234** [comment]
Let me put one more update before you merge !

**Comment by dvdvideo1234** [comment]
@thegrb93 
Hmm I guess it will be better to close this PR and make it as a separate addon.

**Comment by thegrb93** [comment]
I guess. I've seen some e2 extensions on workshop so maybe that would work.

**Comment by dvdvideo1234** [comment]
@thegrb93 Yeah. I will not have to wait a hundred years for review and another [thousand](http://mlp.wikia.com/wiki/Princess_Luna) to get merged.

**Comment by dvdvideo1234** [comment]
You can delete the PR now. The information about the patch is now outdated and it does not correspond to the current revision.

**Comment by thegrb93** [comment]
@dvdvideo1234 I can probably review it now that I'm a part of the team

**Comment by dvdvideo1234** [comment]
@thegrb93

Hello, would you like me to make another PR of the current version? If so, I must create the PR that contains exactly: https://github.com/dvdvideo1234/ControlSystemsE2

**Comment by thegrb93** [comment]
Sure

**Comment by dvdvideo1234** [comment]
@thegrb93 

> 
> I guess. I've seen some e2 extensions on workshop so maybe that would work.

How often do you intend on reviewing and merging such PR?

**Comment by thegrb93** [comment]
I try to get PR asap since it's basically finished code. Issues take a little more motivation.

**Comment by dvdvideo1234** [comment]
@thegrb93 

Ah, that's the case then. I will open another PR, for merging [my control theory addon](https://steamcommunity.com/sharedfiles/filedetails/?id=1440897301) into wire-extras, but I will not delete [my personal repository](https://github.com/dvdvideo1234/ControlSystemsE2), to have my backups, while I add stuff to it and it grows exponentially. I will have to update this in two places, but I think it is safer if something happens. In the current state, my personal repo will receive the updated first then wire-extras will be second. I will remove it from [the workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1440897301) the extras are shipped with the workshop version of wiremod. Actually i feel kinda in the middle of this. I want to help the community, but it is sad that so few people seem to care. :+1: 

Do the extras get shipped with the [workshop version of wiremod](https://steamcommunity.com/sharedfiles/filedetails/?id=160250458) ?

**Pull request closed without merging**
