### PR TITLE
Added: Better remove handling over direct entity hit list

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
Is it OK, @thegrb93 ?

**Comment by thegrb93** [comment]
Can you change gsVarName..gsCbcHash to varMethSkip:GetName().."_skip" and get rid of those two vars?

**Comment by dvdvideo1234** [comment]
Yes, but I have to put this in 4 placesee below:
```lua
cvars.RemoveChangeCallback(varMethSkip:GetName(), varMethSkip:GetName()..gsCbcHash)
cvars.AddChangeCallback(varMethSkip:GetName(), function(sVar, vOld, vNew)
	gtMethList.SKIP = convArrayKeys(("/"):Explode(tostring(vNew or gsZeroStr)))
end, varMethSkip:GetName()..gsCbcHash)
```
Instead of
```lua
gsVarName = varMethSkip:GetName()
cvars.RemoveChangeCallback(gsVarName, gsVarName..gsCbcHash)
cvars.AddChangeCallback(gsVarName, function(sVar, vOld, vNew)
	gtMethList.SKIP = convArrayKeys(("/"):Explode(tostring(vNew or gsZeroStr)))
end, gsVarName..gsCbcHash)
```

**Comment by dvdvideo1234** [comment]
@thegrb93, I guess your request is for me to remove
```lua
local gsVarName = "" -- This stores current variable name
local gsCbcHash = "_call" -- This keeps suffix realted to the file
```

**Comment by thegrb93** [comment]
Yea

**Comment by thegrb93** [comment]
It looks fine, but cleaning up those would make it a bit better.

**Comment by dvdvideo1234** [comment]
Done.

**Pull request merged**
