### PR TITLE
Sync dumpItem/dumpInfo

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by thegrb93** [comment]
Why rename?

**Comment by dvdvideo1234** [comment]
To match the naming convention <lower>X3<camel_case>

**Comment by thegrb93** [comment]
No, the other functions vary in name length a bit too and dump is fine the way it is. I would argue that cpy should be copy, but best not to rename that either.

**Comment by dvdvideo1234** [comment]
I've added a backwards compatibility alias so should be all good. Whoever wants to use `dump` is welcome to use it.

**Comment by dvdvideo1234** [comment]
I guess you are right

**Comment by thegrb93** [comment]
I don't think dump should be changed to dmp

**Pull request closed without merging**
