### PR TITLE
fix gui wiring

### PR DESCRIPTION
**Pull request by mms92**
the tool was not working , probably due to some scope problem with the variable , i changed the library used to trigger the var initialisation , draw of the gui and wirelink reception , from usermessage to net
von indexed localy from WireLib.von
followup of https://github.com/wiremod/wire-extras/pull/53

### CODE REVIEW

**Comment by thegrb93** [comment]
Strange. I just tested it again and got this error
```
[ERROR] addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:350: bad argument #1 to 'pairs' (table expected, got string)
  1. pairs - [C]:-1
   2. SetComponent - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:350
    3. GUIWiring_ShowGUI - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:258
     4. func - addons/wire-extras/lua/weapons/gmod_tool/stools/gui_wiring.lua:126
      5. unknown - lua/includes/extensions/net.lua:32
```

**Comment by thegrb93** [comment]
I just created an 'Add' gate and constant value and selected them both and pushed r.

**Comment by mms92** [comment]
raaa

**Comment by mms92** [comment]
fiou , found the problem, that shitty problem

**Comment by mms92** [comment]
so next , wirelink problem

**Comment by mms92** [comment]
fiexd , oof, any problems left ? otherwise it's good

**Comment by mms92** [comment]
@thegrb93

**Comment by thegrb93** [comment]
Let me try

**Pull request merged**
