### PR TITLE
Replaced utilx with util library

### PR DESCRIPTION
**Pull request by UAVXP**

### CODE REVIEW

**Comment by oldmud0** [comment]
Yeah

**Comment by Divran** [comment]
Was the utilx library removed? Anyway might as well replace it with `player:GetEyeTrace()` instead http://wiki.garrysmod.com/page/Player/GetEyeTrace

**Comment by bigdogmat** [comment]
It was removed when Gmod 13 came out. Also do what @Divran said, because `GetCursorAimVector` no longer exists.

**Comment by bigdogmat** [comment]
Now it's equal to what http://wiki.garrysmod.com/page/Player/GetEyeTrace does internally, might as well just use it

**Comment by UAVXP** [comment]
So what's the difference then? I just want to leave the code as it's meant to be

**Comment by bigdogmat** [comment]
[This](https://github.com/garrynewman/garrysmod/blob/784cd57576d85712fa13a7cea3a9523b4df966b0/garrysmod/gamemodes/base/gamemode/obj_player_extend.lua#L175-L188) is what http://wiki.garrysmod.com/page/Player/GetEyeTrace does internally, it's exactly the same as what you have now, except it does frame by frame caching.

**Comment by UAVXP** [comment]
Okay, I see difference now, it's cached

**Pull request merged**
