### PR TITLE
Fixed lightBrightness and lightDistance

### PR DESCRIPTION
**Pull request by LiddulBOFH**
Previously these just did not work at all

### CODE REVIEW

**Comment by Divran** [comment]
Why rename "distance" to "Size"?

**Comment by LiddulBOFH** [comment]
It's apparently what is supposed to be used now, you can thank garry for
that

**Comment by LiddulBOFH** [comment]
Just got back from dinner, last reply was bad; also did some thinking afterwards, and threw it up to my limited knowledge of lua of why I did that name change

**Comment by Divran** [comment]
Are you sure it only works if you change distance to Size? If it works fine with distance I don't see a need to change it, but if having it called distance somehow breaks it then it's fine to change it to Size

**Comment by TomyLobo** [comment]
bah, that whole light.lua would have never gone through my review.
All the local functions are UpperCamelCase
UpperCamelCase functions can at worst collide with Garry's and at best are easily confused with Garry's.
Don't do that.

**Comment by Divran** [comment]
Yeah but that was yeeeeeeeeeears ago

**Comment by TomyLobo** [comment]
so, fix both :)

**Comment by Divran** [comment]
effort tho

**Pull request merged**
